stages:
  - compute
  - plot
  - tabulate
  - tex

variables:
  DIJITSO_CACHE_DIR: $CI_PROJECT_DIR/.cache/dijitso
  GIT_STRATEGY: fetch

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .cache/dijitso
    - numericals/zeroguess
    - numericals/rampdown

numericals:
  stage: compute
  image: optipulsproject/optipuls
  script: make numericals.all
  only:
    refs:
      - master
  artifacts:
    paths:
      - numericals/zeroguess
      - numericals/rampdown

plots:
  stage: plot
  image: optipulsproject/optipuls
  script: make plots.all
  only:
    refs:
      - master
  artifacts:
    paths:
      - plots/coefficients
      - plots/optimized

tables:
  stage: tabulate
  image: optipulsproject/tabulate
  script: make tables.all
  only:
    refs:
      - master
  artifacts:
    paths:
      - tables/zeroguess.tex
      - tables/rampdown.tex

tex:
  stage: tex
  image: numapde/publications
  script: make preprint
  only:
    refs:
      - master
  artifacts:
    paths:
      - manuscript-numapde-preprint.pdf
