stages:
  - compute
  - plot
  - tabulate
  - tex

numericals:
  stage: compute
  image: optipuls
  script: make numericals.all
  only:
    refs:
      - master
  artifacts:
    paths:
      - numericals/zeroguess
      - numericals/rampdown

plots:
  stage: plot
  image: optipuls
  script: make plots.all
  only:
    refs:
      - master
  artifacts:
    paths:
      - plots/coefficients
      - plots/optimized

tables:
  stage: tabulate
  image: tabulate
  script: make tables.all
  only:
    refs:
      - master
  artifacts:
    paths:
      - tables/zeroguess.tex
      - tables/rampdown.tex

tex:
  stage: tex
  image: numapde/publications
  script: make preprint
  only:
    refs:
      - master
  artifacts:
    paths:
      - manuscript-numapde-preprint.pdf
